-- Création de la base de données ASTA_ACF2L
CREATE DATABASE ASTA_ACF2L;

-- Utilisation de la base de données ASTA_ACF2L
USE ASTA_ACF2L;

-- Création de la table USER
CREATE TABLE USER (
    USER_ID INT PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(100),
    BIRTHDATE DATE,
    ADRESSE VARCHAR(200),
    ROLE VARCHAR(50)
);

-- Création de la table PILOTES
CREATE TABLE PILOTES (
    ID_PILOTES INT PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    BIRTHDATE DATE,
    TYPE_AVION VARCHAR(50)
);


-- Création de la table ADHERENTS
CREATE TABLE ADHERENTS (
    ADHERENT_ID INT PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(100),
    BIRTHDATE DATE,
    ADRESSE VARCHAR(200),
    ROLE VARCHAR(50)
);

-- Création de la table AVIONS

CREATE TABLE AVIONS (
    ID_AVIONS INT PRIMARY KEY,
    ID_PILOTES INT,
    MODELE VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    TEMPERATURE_CONSEILLEE INT,
    FOREIGN KEY (ID_PILOTES) REFERENCES PILOTES(ID_PILOTES)
);

