-- Création de la base de données ASTA_ACF2L
CREATE DATABASE ASTA_ACF2L;

-- Utilisation de la base de données ASTA_ACF2L
USE ASTA_ACF2L;

-- Création de la table USER
CREATE TABLE ASTA_USER (
    USER_ID INT PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(100),
    BIRTHDATE DATE,
    ADRESSE VARCHAR(200),
    ROLE VARCHAR(50)
);

-- Création de la table PILOTES
CREATE TABLE ASTA_PILOTES (
    ID_PILOTES INT PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    BIRTHDATE DATE,
    TYPE_AVION VARCHAR(50)
);


-- Création de la table ADHERENTS
CREATE TABLE ASTA_ADHERENTS (
    ADHERENT_ID INT PRIMARY KEY,
    NOM VARCHAR(50),
    PRENOM VARCHAR(50),
    CIVILITE VARCHAR(50),
    SITUATION VARCHAR(50),
    TEL VARCHAR(50),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(100),
    BIRTHDATE DATE,
    ADRESSE VARCHAR(200),
    ROLE VARCHAR(50)
);

-- Création de la table AVIONS

CREATE TABLE ASTA_AVIONS (
    ID_AVIONS INT PRIMARY KEY,
    ID_PILOTES INT,
    MODELE VARCHAR(50),
   CAPACITE VARCHAR(200),
   POIDS_A_VIDE INT,
   AUTONOMIE INT,
   CONSSOMATION VARCHAR(50),
   DESCRIPTION VARCHAR(1000),

    FOREIGN KEY (ID_PILOTES) REFERENCES ASTA_PILOTES(ID_PILOTES)
);
CREATE TABLE `ASTA_RESERVATION` (
  `RESERVATION_ID` int(11) NOT NULL,
  `ADHERENT_ID` int(11) DEFAULT NULL,
  `ID_PILOTES` int(11) DEFAULT NULL,
  `DATE_RESERVATION` date DEFAULT NULL,
  `HEURE_RESERVATION` time DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
    PRIMARY KEY (RESERVATION_ID),
    FOREIGN KEY (ADHERENT_ID) REFERENCES ASTA_ADHERENTS(ADHERENT_ID),
    FOREIGN KEY (ID_PILOTES) REFERENCES ASTA_PILOTES(ID_PILOTES)
); 


  